function gui_params(main_handle, paramInit, colorFgd, colorBgd, colorBut, colorCurie)
    filepath = fileparts(mfilename('fullpath'));

    if (isempty(paramInit))
        params_default = {...
        '0.065';... resXY
        '0.200';... resZ
        '62';...    max nucleus diameter
        '2:3';...   spot size
        '0';...     Z slices to skip
        'GFP';...   signal tag
        'false';... low signal
        'true';...  use cellpose
        '';...      nb of std above mean
        '0';...     nb of pixels to add to contours
        'yAT';...   yeast indicator
        'DAPI';...  nuclei tag
        'cyto';...  model
        '30';...    cellDiameter
        'false'}; % useEnsemble
    else
        params_default= paramInit;
    end

    rangeZ2skip = categorical(-5:5);
    cpmodels = categorical(["cyto", "cyto2", "CP", "CPx", "nuclei"]);

    % Main param figure
    paramspanel = figure('Visible','on','Position',[00,000,500,400],...
        'Color',colorBgd,'Resize','on',...
        'Name', 'NuFoQal parameters',...
        'NumberTitle', 'off',...
        'MenuBar', 'none');
    movegui(paramspanel, 'center');

    % Panels
    tags_panel = uipanel('Parent',paramspanel,'Title','Data information',...
    'Position',[.05 .05 .4375 .9], 'FontWeight', 'bold', ...
    'BackgroundColor',colorBgd,...
    'ForegroundColor',colorCurie);

    segmentation_panel = uipanel('Parent',paramspanel,'Title','Segmentation',...
    'Position',[.5125 .5 .4725 .45], 'FontWeight', 'bold', ...
    'BackgroundColor',colorBgd,...
    'ForegroundColor',colorCurie);

    cellpose_panel = uipanel('Parent',paramspanel,'Title','Cellpose settings',...
    'Position',[.5125 .2 .4725 .3], 'FontWeight', 'bold', ...
    'BackgroundColor',colorBgd,...
    'ForegroundColor',colorFgd);

    % Image/Logo
    pathImgUI=strcat([filepath,filesep,'Logo_small.png']);%'institut_curie.png']);
    [imageLogo, ~, alpha] = imread(pathImgUI);
    Logo_panel=uipanel('Parent',paramspanel,...
        'Position',[0.5125,0.05,0.1540,0.125],...
        'BorderWidth', 1,...
        'BackgroundColor',colorBut,...
        'ForegroundColor',colorFgd);
    ax = axes('parent',Logo_panel,'units','normalized','position',[0 0 1 1]);
    f=image(imageLogo,'parent',ax);
    axis off;
    set(f, 'AlphaData', alpha);

    % tags panel content
    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Signal channel name', ...
        'Units','normalized', 'Position', [0.05,0.9,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{6}, 'Units','normalized', ...
        'Position', [0.7,0.9,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd, ...
        'Callback', @input_sigName_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Nuclei channel name', ...
        'Units','normalized', 'Position', [0.05,0.8,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{12}, 'Units','normalized', ...
        'Position', [0.7,0.8,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd, ...
        'Callback', @input_nucTag_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Yeast indicator', ...
        'Units','normalized', 'Position', [0.05,0.70,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{11}, 'Units','normalized', ...
        'Position', [0.7,0.7,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd, ...
        'Callback', @input_yeastIndic_callback);

    uicontrol('Parent', tags_panel, 'Style', 'checkbox', ...
        'String', ' Low signal to noise ratio', 'Units','normalized', ...
        'Position', [0.05,0.5875,0.9,0.075], 'HandleVisibility','off', ...
        'HorizontalAlignment', 'right', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd, ...
        'Callback', @checkbox_lowSig_callback);


    % acquisition panel content
    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', sprintf('XY pixel size (%sm)', char(hex2dec('03BC'))), ...
        'Units','normalized', 'Position', [0.05,0.475,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{1}, 'Units','normalized', ...
        'Position', [0.7,0.475,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd,...
        'Callback', @input_XY_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', sprintf('Z pixel depth (%sm)', char(hex2dec('03BC'))), ...
        'Units','normalized', 'Position', [0.05,0.375,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{2}, 'Units','normalized', ...
        'Position', [0.7,0.375,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd,...
        'Callback', @input_Z_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Spot size in pixel', ...
        'Units','normalized', 'Position', [0.05,0.25,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{4}, 'Units','normalized', ...
        'Position', [0.7,0.25,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd,...
        'Callback', @input_spotSize_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Maximum nucleus radius', ...
        'Units','normalized', 'Position', [0.05,0.085,0.60,0.15], ...
        'HandleVisibility','off', 'Max', 2,...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent', tags_panel, 'Style', 'edit', ...
        'String', params_default{3}, 'Units','normalized', ...
        'Position', [0.7,0.15,0.25,0.075], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd,...
        'Callback', @input_maxNuc_callback);

    uicontrol('Parent', tags_panel, 'Style', 'text', ...
        'String', 'Z slices to skip', ...
        'Units','normalized', 'Position', [0.05,0.015,0.60,0.075], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent',tags_panel, ...
        'Style','popupmenu','String', rangeZ2skip,...
        'Units','normalized','Position',[0.7,0.025,0.25,0.075],...
        'Value', find(rangeZ2skip == params_default{5}),...
        'HandleVisibility','off', ...
        'BackgroundColor',colorBut,...
        'ForegroundColor',colorFgd,...
        'Callback',@popup_Z2skip_callback); 


    % segmentation panel content
    uicontrol('Parent',segmentation_panel, ...
        'Style','CheckBox','String',' Use CellPose for nuclei',...
        'Units','normalized','Position',[0.05,0.8,0.90,0.15],...
        'HandleVisibility','off', 'Value', eval(params_default{8}),...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd,...
        'ForegroundColor',colorFgd,...
        'Callback',@checkbox_cellpose_callback);

    uicontrol('Parent', segmentation_panel, 'Style', 'text', ...
        'String', 'Number of std above mean to define spots', ...
        'Units','normalized', 'Position', [0.05,0.275,0.6,0.4], ...
        'HandleVisibility','off', 'Max', 3,...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    uicontrol('Parent',segmentation_panel, ...
        'Style','edit','String', params_default{9},...
        'Units','normalized','Position',[0.7,0.475,0.25,0.15],...
        'HandleVisibility','off', ...
        'BackgroundColor',colorBut,...
        'ForegroundColor',colorFgd,...
        'Callback',@input_nSig_callback);

    uicontrol('Parent',segmentation_panel, ...
        'Style','text','String','Pixels to add on nuclei contours',...
        'Units','normalized','Position',[0.05,0.01,0.6,0.3],...
        'HandleVisibility','off', 'Max', 2,...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd,...
        'ForegroundColor',colorFgd);

    uicontrol('Parent',segmentation_panel, ...
        'Style','popupmenu','String', rangeZ2skip,...
        'Units','normalized','Position',[0.7,0.125,0.25,0.15],...
        'Value', find(rangeZ2skip == params_default{10}),...
        'HandleVisibility','off', ...
        'BackgroundColor',colorBut,...
        'ForegroundColor',colorFgd,...
        'Callback', @popup_pix2add_callback); 

    % cellpose panel content
    text_model = uicontrol('Parent', cellpose_panel, 'Style', 'text', ...
        'String', 'Cellpose model', ...
        'Units','normalized', 'Position', [0.05,0.7,0.60,0.25], ...
        'HandleVisibility','off', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    pop_model = uicontrol('Parent', cellpose_panel, 'Style', 'popupmenu', ...
        'String', cpmodels, 'Value', find(cpmodels == params_default{13}), ...
        'Units','normalized', ...
        'Position', [0.7,0.75,0.25,0.25], 'HandleVisibility','off', ...
        'BackgroundColor',colorBut, 'ForegroundColor',colorFgd,...
        'Callback', @popup_cpmodel_callback);

    text_cellDiam = uicontrol('Parent', cellpose_panel, 'Style', 'text', ...
        'String', 'Nucleus Diameter', ...
        'Units','normalized', 'Position', [0.05,0.35,0.60,0.25], ...
        'HandleVisibility','off',...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd);

    input_cellDiam = uicontrol('Parent',cellpose_panel, ...
        'Style','edit','String', params_default{14},...
        'Units','normalized','Position',[0.7,0.375,0.25,0.25],...
        'HandleVisibility','off', ...
        'BackgroundColor',colorBut,...
        'ForegroundColor',colorFgd,...
        'Callback', @input_cellDiam_callback);

    checkbox_useEns = uicontrol('Parent', cellpose_panel, 'Style', 'checkbox', ...
        'String', '  use ensemble of models', 'Units','normalized', ...
        'Position', [0.05,0.05,0.9,0.25], 'HandleVisibility','off', ...
        'HorizontalAlignment', 'right', 'Value', 0, 'Max', 2,...
        'BackgroundColor',colorBgd, 'ForegroundColor',colorFgd, ...
        'Callback', @checkbox_useEns_callback);

    % Store parameters inside gui_params
    setappdata(paramspanel, 'cphandles', [pop_model, input_cellDiam, checkbox_useEns, text_model, text_cellDiam]);
    setappdata(paramspanel, 'mainH', main_handle);
    setappdata(paramspanel,'allparams',params_default);
    setappdata(paramspanel, 'colors', cat(1, colorFgd, colorBgd, colorBut, colorCurie));

    % OK button
    uicontrol('Parent',paramspanel,'Style','pushbutton',...
    'String','DONE', 'FontSize', 20, 'fontWeight', 'Bold', ...
    'Units','normalized','Position',[0.685,0.05,0.3,0.125],...
    'TooltipString', 'Generate figures from the analysis conducted on the selected files',...
    'BackgroundColor',colorBut,...
    'ForegroundColor',colorCurie,...
    'Callback',{@ok_button_Callback});
end

%% Callback functions
% Tags panel
function input_sigName_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{6} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function input_nucTag_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{12} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function input_yeastIndic_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{11} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function checkbox_lowSig_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    if source.Value
        allparams{7} = 'true';
    else
        allparams{7} = 'false';
    end

    setappdata(gcbf, 'allparams', allparams);
end

% Acquisition panel
function input_XY_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{1} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function input_Z_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{2} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function input_spotSize_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{4} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function input_maxNuc_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{3} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end
function popup_Z2skip_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{5} = source.String{source.Value};

    setappdata(gcbf, 'allparams', allparams);
end

% Segmentation panel
function checkbox_cellpose_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    if source.Value
        allparams{8} = 'true';
    else
        allparams{8} = 'false';
    end

    % Lock / unlock cellpose panel
    handlesArray = getappdata(gcbf, 'cphandles');
    if source.Value
        handlesArray(1).Parent.ForegroundColor = [0 0 0];
        set(handlesArray, 'Enable', 'on');
    else
        handlesArray(1).Parent.ForegroundColor = [.5 .5 .5];
        set(handlesArray, 'Enable', 'off');
    end

    setappdata(gcbf, 'allparams', allparams);
end

function input_nSig_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{9} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function popup_pix2add_callback(source,  ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{10} = source.String{source.Value};

    setappdata(gcbf, 'allparams', allparams);
end

% Cellpose panel
function popup_cpmodel_callback(source, ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{13} = source.String{source.Value};

    setappdata(gcbf, 'allparams', allparams);
end

function input_cellDiam_callback(source, ~)
    allparams = getappdata(gcbf, 'allparams');
    allparams{14} = source.String;

    setappdata(gcbf, 'allparams', allparams);
end

function checkbox_useEns_callback(source, ~)
    allparams = getappdata(gcbf, 'allparams');
    if source.Value
        allparams{15} = 'true';
    else
        allparams{15} = 'false';
    end

    setappdata(gcbf, 'allparams', allparams);
end

function ok_button_Callback(~, ~)
    allparams = getappdata(gcbf, 'allparams');
    mainH = getappdata(gcbf, 'mainH');

    setappdata(mainH, 'PARAMS', allparams);

    close(gcbf);

    return
end