function [X,Y,Z,Volume,Intensity,Relativeintensity,Distancetoborder,Relativedistancetoborder,NucleusID,Nucleusintensity,Nucleusbackground,NucleusVolume,Nucleusspotnumber,Tokeep,Elongation] = importSpots(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [X,Y,Z,VOLUME,INTENSITY,RELATIVEINTENSITY,DISTANCETOBORDER,RELATIVEDISTANCETOBORDER,NUCLEUSID,NUCLEUSINTENSITY,NUCLEUSBACKGROUND,NUCLEUSVOLUME,NUCLEUSSPOTNUMBER,TOKEEP]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [X,Y,Z,VOLUME,INTENSITY,RELATIVEINTENSITY,DISTANCETOBORDER,RELATIVEDISTANCETOBORDER,NUCLEUSID,NUCLEUSINTENSITY,NUCLEUSBACKGROUND,NUCLEUSVOLUME,NUCLEUSSPOTNUMBER,TOKEEP]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [X,Y,Z,Volume,Intensity,Relativeintensity,Distancetoborder,Relativedistancetoborder,NucleusID,Nucleusintensity,Nucleusbackground,NucleusVolume,Nucleusspotnumber,Tokeep]
%   = importfile('yAT191-YPD-DO1-cmos-2_w3GFP-Cam-C-Mos.nucs',2, 1026);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/11/07 10:42:20

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
X = dataArray{:, 1};
Y = dataArray{:, 2};
Z = dataArray{:, 3};
Volume = dataArray{:, 4};
Intensity = dataArray{:, 5};
Relativeintensity = dataArray{:, 6};
Distancetoborder = dataArray{:, 7};
Relativedistancetoborder = dataArray{:, 8};
NucleusID = dataArray{:, 9};
Nucleusintensity = dataArray{:, 10};
Nucleusbackground = dataArray{:, 11};
NucleusVolume = dataArray{:, 12};
Nucleusspotnumber = dataArray{:, 13};
Tokeep = dataArray{:, 14};
Elongation = dataArray{:, 15};
